### ISSUE TITLE
Wrong species list file in main script

### ISSUE THREAD

**Issue by oharar** [AdamCSmithCWS/Estimating_Change_in_NorthAmerican_Birds#1]
In 
popest = read.csv("Rosenberg et al species list - Copy.csv",
                   stringsAsFactors = F)

the file should be "Rosenberg et al species list.csv"

**Comment by AdamCSmithCWS** [comment]
Thank you. I've fixed it now.

**Comment by laura-martinez00** [comment]
I am attempting to replicate the graph published by the New York Times, specifically the S1, by any chance do you have the clean dataset to start working directly with that? I attempted to run the code and for some reason some bits won´t work
